export enum GameStatus {
  DeckEmpty = 'deck-empty',
  SecondChanceSurvived = 'second-chance-survived',
  Busted = 'busted',
  Flip7 = 'flip-7',
  FlipThreeComplete = 'flip-three-complete',
  FreezeBanked = 'freeze-banked',
  SecondChanceAcquired = 'second-chance-acquired',
  Banked = 'banked',
  CannotBankBusted = 'cannot-bank-busted',
  CannotBankDuringFlipThree = 'cannot-bank-during-flip-three',
  Flipped = 'flipped',
  Flip7BonusAwarded = 'flip-7-bonus-awarded',
  ChoicePoint = 'choice-point',
  NoFlipsRemaining = 'no-flips-remaining',
  CannotPassDuringFlipThree = 'cannot-pass-during-flip-three',
  PassingDisabled = 'passing-disabled',
  PlayerPassed = 'player-passed',
}
