name: Update Coverage Badge

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Tests & Lint"]
    types:
      - completed

jobs:
  update-badge:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor # Only run for the repo owner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Extract coverage percentage
      id: coverage
      run: |
        COVERAGE=$(node -e "
          try {
            const coverage = require('./coverage-summary.json');
            const pct = Math.round(coverage.summary?.lines?.pct || coverage.lines?.pct || 0);
            console.log(pct);
          } catch(e) {
            console.log(0);
          }
        ")
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
        
        # Determine color
        if [ $COVERAGE -ge 80 ]; then
          COLOR="brightgreen"
        elif [ $COVERAGE -ge 60 ]; then
          COLOR="yellow"  
        elif [ $COVERAGE -ge 40 ]; then
          COLOR="orange"
        else
          COLOR="red"
        fi
        echo "color=$COLOR" >> $GITHUB_OUTPUT
        
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: coverage-badge.json
        label: coverage
        message: ${{ steps.coverage.outputs.percentage }}%
        color: ${{ steps.coverage.outputs.color }}
        cacheSeconds: 300
