name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x
      - name: Build Vite app
        run: npm run build
      - name: Serve build
        run: npx serve -s dist &
      - name: Wait for server
        run: npx wait-on http://localhost:3000
      - name: Run Lighthouse CI
        run: lhci autorun --collect.url=http://localhost:3000/index.html || echo "LHCI finished with non-zero exit code"
